development: &development

 twitter:
     key: tvy3oyXU5kdIkZFJr6Fjqvycr
     secret: Y2pO7ilI7cP4iX4DBhgsrQIYtyzXbPWlbLruMg9cADibJy9LQd
 facebook: 
     key: '274024569635379'
     secret: 'e32756e993a65d63024bd82d6dd87051'

production: &production

 twitter:
     key: tvy3oyXU5kdIkZFJr6Fjqvycr
     secret: Y2pO7ilI7cP4iX4DBhgsrQIYtyzXbPWlbLruMg9cADibJy9LQd
 facebook: 
     key: '274024569635379'
     secret: 'e32756e993a65d63024bd82d6dd87051'
