# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &default_twitter
  twitter_api_key: 'tvy3oyXU5kdIkZFJr6Fjqvycr'
  twitter_api_secret: 'Y2pO7ilI7cP4iX4DBhgsrQIYtyzXbPWlbLruMg9cADibJy9LQd'

default_facebook: &default_facebook
  facebook_api_key: '1766599203582835' 
  facebook_api_secret: 'd26d5e061f87dd1394d851770a397148'

development:
  secret_key_base: 82bd1c8e4027ceb95bead5a5eaa3d3c23635c92b2b67f08036327ac48f6c5049cbc9e84f521917b9355c9e7fe2de82ee5a32493b3e76bf0193073df4a26a48cb
  <<: *default_twitter
  <<: *default_facebook

test:
  secret_key_base: e2304a0d633a33ec0ea55e972e3de0cf978d2201670e7fbd6e594c1edfa0187ad2704e437c02ee32c69bc7a26f9842571274be1614a9f903c636ec2468d32eaa
  <<: *default_twitter
  <<: *default_facebook

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 83952623e50fd8ecfee4ee4a45bd1dc6f9f20f00d552b269742253c4d275006ea0ed8c1f1566c0bfb3f631012b0ec4f037987640ce761f887bcbb9d1003a2d20
  <<: *default_twitter
  <<: *default_facebook

